### PR TITLE
fix incorrect coder version in composer.json

### PR DESCRIPTION
**Pull request by NewZeal**
Coder version 8.2 replaced with 2.0

### CODE REVIEW

**Comment by RoySegall** [comment]
Thanks for the PR. Hope to get this one tomorrow. I'm a bit short with the time in the past couple of months. 

Anyway, is this relate to a similar issue in the message module?

**Comment by NewZeal** [comment]
Yes, it is similar.  However, the fix for the message module does not pass Travis tests on github, so not sure what to do right now.

**Comment by NewZeal** [comment]
Is it necessary to have a requirement for coder module in a contrib module?  On our system we are running codesniffer as part of the deploy system.  By requiring coder, we are not actually running it are we?  It is not an actual module dependency.  If it was it would be referenced in message_ui.info.yml.

**Comment by RoySegall** [comment]
TBH -  I don't recall the coder module in any case. I might have been a copy-paste issue. I can see you removed this part in the last commit but travis did not run yet so I don't how this will affect our travis.

**Comment by NewZeal** [comment]
Ok, I think I know what the fix is.  It is actually only the message_ui module that is failing the build.  According to jhedstrom from message module, you should be using require-dev and not require:

> That's why it's specified as require-dev, rather than require. Composer will not pull in vendor require-dev dependencies, only the top-level require-dev libraries specified in your composer.json.

**Comment by RoySegall** [comment]
Well... if @jhedstrom said it it must be true. I'd put life on this one :)

Anyway, I need to see why Travis isn't triggered for your PR - I'll check this one when I have the time.

And thanks again for the PR.

**Comment by NewZeal** [comment]
I'm able to install message_ui by leaving it out of the require declarations in composer.json and relying on other message modules to load it using their own dependency requirements in drupal.  

The requested change should still be merged once all checks are done.

**Comment by NewZeal** [comment]
OK, so the module fails Travis checks on our github account for the same reasons:
 ```
Problem 1
    - drupal/message_ui 1.x-dev requires drupal/coder ^8.2 -> no matching package found.
    - drupal/message_ui dev-1.x requires drupal/coder ^8.2 -> no matching package found.
    - drupal/message_ui 1.0.0-beta1 requires drupal/coder ^8.2 -> no matching package found.
    - drupal/message_ui 1.0.0-beta2 requires drupal/coder ^8.2 -> no matching package found.
    - drupal/message_private 1.0.0-alpha1 requires drupal/message_ui * -> satisfiable by drupal/message_ui[1.0.0-beta2, 1.0.0-beta1, dev-1.x, 1.x-dev].
    - drupal/message_private 1.0.0-alpha2 requires drupal/message_ui * -> satisfiable by drupal/message_ui[1.0.0-beta2, 1.0.0-beta1, dev-1.x, 1.x-dev].
    - drupal/message_private 1.0.0-alpha3 requires drupal/message_ui * -> satisfiable by drupal/message_ui[1.0.0-beta2, 1.0.0-beta1, dev-1.x, 1.x-dev].
    - drupal/message_private 1.x-dev requires drupal/message_ui * -> satisfiable by drupal/message_ui[1.0.0-beta2, 1.0.0-beta1, dev-1.x, 1.x-dev].
    

```
@RoySegall any chance you could perhaps sneak this change into at least the dev branch?  Thanks.

**Comment by NewZeal** [comment]
Closing this PR to request a further one to trigger Travis and to make a simpler request.

**Comment by RoySegall** [comment]
I'll try this afternoon(Tel Aviv time) to run this on my local machine. If that was a success I'll credit you and push.

**Pull request closed without merging**
