### PR TITLE
Start to fix the tests.

### PR DESCRIPTION
**Pull request by RoySegall**
#11

### CODE REVIEW

**Comment by RoySegall** [comment]
Before merging this one we need to fix https://github.com/Gizra/message/issues/174

**Comment by RoySegall** [comment]
Merging this one since it's got bigger and keep working in #22.

**Comment by mccrodp** [comment]
Great job, @RoySegall! 😄

**Comment by RoySegall** [comment]
10x. The tests says that the module is OK but we need someone to test it manually.

**Pull request merged**
