### PR TITLE
More indentation fixes.

### PR DESCRIPTION
**Pull request by RoySegall**

### CODE REVIEW

**Comment by mccrodp** [comment]
@RoySegall I have the following set in PHPStorm. I'm not sure whats happening (unless I missed some files) as I thought I reformatted all code in this module.

screen shot 2016-08-05 at 15 06 12

**Comment by RoySegall** [comment]
it's been a while since I set it up because there is a settings file we use in Gizra - https://github.com/Gizra/KnowledgeBase/wiki/Ubuntu-and-development-environment-setup#php-storm.

If you do use it then set it then would change some of your shortcuts.

**Comment by mccrodp** [comment]
Ok, thanks. Done.

**Comment by RoySegall** [comment]
OK. Finished.

**Pull request merged**
